version: "3.8"
services:
  front:
    build:
      context: .
      dockerfile: ./build/local/Dockerfile
    volumes:
      - ./src:/usr/src/front/src
      - ./public:/usr/src/front/public
    ports:
      - "5173:5173"
    env_file:
      - .env
    networks:
      - vite

networks:
  vite:
    external: true
